version: '3.8'

services:
  db:
    image: 'postgres'
    env_file:
      - db.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - 5432

  equip_api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - 4002:4002
    command: bash -c "yarn && yarn migration:generate && yarn migration:run &&  && yarn dev"

